#!/usr/bin/env zsh

# Clone zgen if you haven't already
if [[ ! -f $HOME/.zgen/zgen.zsh ]]; then
  pushd $HOME
  git clone git@github.com:tarjoilija/zgen.git .zgen
  popd
fi
source $HOME/.zgen/zgen.zsh

# if the init scipt doesn't exist
if ! zgen saved; then

  zgen oh-my-zsh
  zgen oh-my-zsh plugins/aws
  zgen oh-my-zsh plugins/bundler
  zgen oh-my-zsh plugins/chruby
  zgen oh-my-zsh plugins/colored-man-pages
  zgen oh-my-zsh plugins/fabric
  zgen oh-my-zsh plugins/gem
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/github
  zgen oh-my-zsh plugins/golang
  zgen oh-my-zsh plugins/pip
  zgen oh-my-zsh plugins/python
  zgen oh-my-zsh plugins/redis-cli
  zgen oh-my-zsh plugins/rsync
  zgen oh-my-zsh plugins/sudo
  zgen oh-my-zsh plugins/vagrant

  if [ $(uname -a | grep -ci Darwin) = 1 ]; then
    # Load OSX-specific plugins
    zgen oh-my-zsh plugins/osx
  fi

  zgen load $HOME/.zsh/hg.zsh
  zgen load $HOME/.zsh/billputer.zsh-theme

  # generate the init script from plugins above
  zgen save
fi
