#!/usr/bin/env zsh



# Clone zgen if you haven't already
if [[ ! -f $HOME/.zgen/zgen.zsh ]]; then
  pushd $HOME
  # add github to known_hosts
  echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' | tee -a ~/.ssh/known_hosts
  git clone https://github.com/tarjoilija/zgen.git ~/.zgen
  popd
fi
source $HOME/.zgen/zgen.zsh

# if the init scipt doesn't exist
if ! zgen saved; then

  zgen oh-my-zsh
  zgen oh-my-zsh plugins/bundler
  zgen oh-my-zsh plugins/gem
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/github
  zgen oh-my-zsh plugins/golang
  zgen oh-my-zsh plugins/pip
  zgen oh-my-zsh plugins/python
  zgen oh-my-zsh plugins/redis-cli
  zgen oh-my-zsh plugins/rsync
  zgen oh-my-zsh plugins/sudo
  zgen oh-my-zsh plugins/vagrant

  if [ $(uname -a | grep -ci Darwin) = 1 ]; then
    # Load macos-specific plugins
    zgen oh-my-zsh plugins/macos
  fi

  if [ -f /usr/local/bin/aws_zsh_completer.sh ]; then
    zgen load /usr/local/bin/aws_zsh_completer.sh
  fi

  # If zsh-syntax-highlighting is bundled after zsh-history-substring-search,
  # they break, so get the order right.
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load zsh-users/zsh-history-substring-search
  zgen load chrissicool/zsh-256color

  zgen load $HOME/.zsh/hg.zsh
  zgen load $HOME/.zsh/set-window-title.zsh
  zgen load $HOME/.zsh/billputer.zsh-theme

  # generate the init script from plugins above
  zgen save
fi
